### ISSUE TITLE
can insert version pls help 

### ISSUE THREAD

**Issue by gamingoninsulin** [Chrotos/datapack-language-server#1]
i wan to use this but its asjing to download a version and insert a version number i ve tryed:

1.21
and or a directlink:
https://github.com/Chrotos/datapack-language-server/releases/download/v0.0.22/1.21.jar but both notting i can smash the enter button but does notting and if i click left mouse somewhere else "No Version Selected"

greetings insulin ;)

**Comment by Katzen48** [comment]
I added some documentation of the extension to the [README.md](https://github.com/Chrotos/datapack-language-server/blob/main/README.md#Configuration) on how to configure the extension.

Please make sure, you have updated the available versions.

Regards,
Katzen48 | Tobi
