### ISSUE TITLE
how to configure server ?

### ISSUE THREAD

**Issue by Futiax** [Chrotos/datapack-language-server#8]

**Comment by Futiax** [comment]
like paper config, op player, world file, ...

**Comment by Katzen48** [comment]
The server is automatically configured.

We decided to not allow accessing the server config, because the server itself is simply used, to make the extension version-independent.
It is not intended to join the server or modify any configuration, as it could negatively impact the function of the extension.

**Comment by Futiax** [comment]
Yes, but how do you get permission then?

**Comment by Katzen48** [comment]
What do you want to get permission for?

**Comment by Futiax** [comment]
Execute command like gamemode or scoreboard or function and schedule

**Comment by Katzen48** [comment]
Do not join the server!
The server is simply for running the validation of your functions.
If you join the server or do stuff on it, the extension is very likely gonna break it.

**Comment by Futiax** [comment]
So we can't test, it's just to check that it starts correctly?

**Comment by Katzen48** [comment]
The extension validates all your functions against the configured version.
It shows (syntax) errors, when the command wouldn't run in the desired version, provides auto completion, a conversion to the 1.20.5 item component format and syntax/semantic highlighting (in the pre-release version).

If you want to test your data packs, please spin up a separate server.

As to why it is discouraged to use the server:
- the extension does a lot of work on the server-side to validate all commands, so doing stuff on the server may decrease the performance
- when validating "summon" commands, the entities are being summoned to check, whether the NBT data, you entered, is valid (that's a limitation on Minecraft's side)
